import os

COMPUTING_UNITS_VARIABLE_NAME = "COMPUTING_UNITS"

if COMPUTING_UNITS_VARIABLE_NAME in os.environ:
    COMPUTING_UNITS = int(os.environ[COMPUTING_UNITS_VARIABLE_NAME])
else:
    COMPUTING_UNITS = 1
